main/default/objects/Fleet__c/Fleet__c.object-meta.xml
<CustomObject>
    <label>Fleet</label>
    <nameField>
        <displayFormat>Fleet-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fleet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Fleet__c/fields/Air_conditioned__c.field-meta.xml
<CustomField>
    <fullName>Air_conditioned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Air conditioned</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Fleet__c/fields/Bus_ID__c.field-meta.xml
<CustomField>
    <fullName>Bus_ID__c</fullName>
    <label>Bus ID</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Fleet__c/fields/Current_status__c.field-meta.xml
<CustomField>
    <fullName>Current_status__c</fullName>
    <defaultValue>&quot;Ready For Use&quot;</defaultValue>
    <label>Current status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled for Maintenance</fullName>
            </value>
            <value>
                <fullName>Undergoing Repairs</fullName>
            </value>
            <value>
                <fullName>Ready For Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Fleet__c/fields/Maximum_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Capacity__c</fullName>
    <label>Maximum Capacity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Fleet__c/fields/Number_of_wheels__c.field-meta.xml
<CustomField>
    <fullName>Number_of_wheels__c</fullName>
    <label>Number of wheels</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Fleet__c/fields/Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Odometer_Reading__c</fullName>
    <label>Odometer Reading</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Fleet__c/fields/Resale_Value__c.field-meta.xml
<CustomField>
    <fullName>Resale_Value__c</fullName>
    <label>Resale Value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Fleet__c/recordTypes/Bus.recordType-meta.xml
<RecordType>
    <fullName>Bus</fullName>
    <active>true</active>
    <label>Bus</label>
</RecordType>

main/default/objects/Fleet_Resale_Calculation__c/Fleet_Resale_Calculation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Fleet Resale Calculation</label>
</CustomObject>

main/default/objects/Fleet_Resale_Calculation__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Fleet_Resale_Calculation__c/fields/Metrics__c.field-meta.xml
<CustomField>
    <fullName>Metrics__c</fullName>
    <label>Metrics</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/classes/FleetTriggerHandler.cls
public class FleetTriggerHandler {
    
    Public static Final Id Bus_FleetRT = Schema.SObjectType.Fleet__c.getRecordTypeInfosByDeveloperName().get('Bus').getRecordTypeId();
    public static Map<String,Fleet_Resale_Calculation__c > defaultConfiguration = Fleet_Resale_Calculation__c.getall();
    
    public static void calculateResaleValue(List<Fleet__c> newFleet, Map<ID, Fleet__c> oldFleetMap, Boolean isInsertOrUndelete, Boolean isUpdate){
        if(newFleet != null && !newFleet.isEmpty()){
            for(Fleet__c fleet : newFleet){
                system.debug('new fleet-- 1 '+fleet);
                //system.debug('new fleet-- 1 '+oldFleetMap.get(fleet.Id));
                system.debug('new RT-- 1 '+fleet.RecordTypeId+'-'+Bus_FleetRT);
                //system.debug('new status-- 1 '+fleet.Current_status__c+'-'+oldFleetMap.get(fleet.Id).Current_status__c);
                //system.debug('new max cap-- 1 '+fleet.Maximum_Capacity__c+'-'+oldFleetMap.get(fleet.Id).Maximum_Capacity__c);
                //system.debug('new year-- 1 '+fleet.Year__c+'-'+oldFleetMap.get(fleet.Id).Year__c);
                if(fleet.RecordTypeId == Bus_FleetRT && fleet.Current_status__c == 'Ready For Use' && String.isNotBlank(fleet.Maximum_Capacity__c) && 
                   (oldFleetMap == null || (oldFleetMap != null && ((fleet.Current_status__c != oldFleetMap.get(fleet.Id).Current_status__c) || 
                                                                    (fleet.Maximum_Capacity__c != oldFleetMap.get(fleet.Id).Maximum_Capacity__c) ||
                                                                    (fleet.Year__c  != oldFleetMap.get(fleet.Id).Year__c ))))){
                                                                        system.debug('new fleet-- 2 '+fleet.Bus_ID__c);
                                                                        computeResaleValueForFleet(fleet);
                                                                    }
            }  
        }
    }
    
    public static void computeResaleValueForFleet(Fleet__c fleet){
        try{
            Decimal sellingPrice = defaultConfiguration.containsKey(fleet.Maximum_Capacity__c+'-Passenger') ? defaultConfiguration.get(fleet.Maximum_Capacity__c+'-Passenger').value__c : 100000;
            if(fleet.Year__c < (defaultConfiguration.containsKey('Fleet Historic Year') ? defaultConfiguration.get('Fleet Historic Year').Metrics__c : 1972)){
                string action = defaultConfiguration.containsKey('Fleet Historic Year') ? defaultConfiguration.get('Fleet Historic Year').Action__c  : 'Increase';
                if(action == 'Increase'){
                    sellingPrice += sellingPrice*(defaultConfiguration.containsKey('Fleet Historic Year') ? defaultConfiguration.get('Fleet Historic Year').value__c : 34)/100; 
                }else{
                    sellingPrice -= sellingPrice*(defaultConfiguration.containsKey('Fleet Historic Year') ? defaultConfiguration.get('Fleet Historic Year').value__c : 34)/100;
                }
            }
            
            if(fleet.Air_conditioned__c){
                string action = defaultConfiguration.containsKey('Air Conditioning') ? defaultConfiguration.get('Air Conditioning').Action__c  : 'Increase';
                if(action == 'Increase'){
                    sellingPrice += sellingPrice*(defaultConfiguration.containsKey('Air Conditioning') ? defaultConfiguration.get('Air Conditioning').value__c : 3)/100; 
                }else{
                    sellingPrice -= sellingPrice*(defaultConfiguration.containsKey('Air Conditioning') ? defaultConfiguration.get('Air Conditioning').value__c : 3)/100;
                }
            }
            if(fleet.Odometer_Reading__c > (defaultConfiguration.containsKey('Millaege') ? defaultConfiguration.get('Millaege').Metrics__c : 100000)){
                string action = defaultConfiguration.containsKey('Millaege') ? defaultConfiguration.get('Millaege').Action__c  : 'Reduce';
                Decimal milesOverReducedPrice = (fleet.Odometer_Reading__c - (defaultConfiguration.containsKey('Millaege') ? defaultConfiguration.get('Millaege').Metrics__c : 100000))*(defaultConfiguration.containsKey('Millaege') ? defaultConfiguration.get('Millaege').value__c : 0.10);
                if(action == 'Reduce'){
                    sellingPrice -= milesOverReducedPrice;
                }else{
                    sellingPrice += milesOverReducedPrice;
                }
            }
            fleet.Resale_Value__c = sellingPrice;
            system.debug('new fleet-- 3'+fleet.Resale_Value__c);
        }catch(Exception ex){
            system.debug('Exception Occurred in computeResaleValueForFleet for :'+fleet+' ::: '+ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<Fleet__c> getFleetInformation(){
        return [SELECT Id, Name, Air_conditioned__c, Bus_ID__c, Current_status__c, Maximum_Capacity__c, Number_of_wheels__c, Odometer_Reading__c, Resale_Value__c, Year__c,Image_URL__c FROM Fleet__c ORDER By LastModifiedDate DESC Limit 50 ];
    }
}